# SETUP
baseurl = "https://vibezurich.com/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "VibeZurich - From idea to app in a Day" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "VibeZurich"
    email = "vibezurich@protonmail.com"

[params]
    description = "VibeZurich - From idea to app in a Day" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
     title = "Email"
    url = "mailto:vibezurich@protonmail.com"
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/vibezurich" # add your linkedin profile URL


[markup.goldmark.renderer]
unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']
